Personal portfolio project
worashf/personal-portfolio pull request #1
Opened 2022-04-20 22:57 UTC by worashf

In these tasks i perform the following activity

1. create mobile navigation
2. add  logo and menu  in main navigation
3. create head line section
4. add  head line heading
5. add head line description
6. create head line social link
7. create  link effect

2022-04-20 23:35 UTC, MeqdamAlqudah requested changes
Hi @worashf , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media4.giphy.com/media/3o6wNGz5IgfyeEXrnq/200.webp?cid=ecf05e470rsk92idplxmrusosv7d5rna7q2zxzybr4kqtf1q&rid=200.webp&ct=g)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-20 23:35 UTC, MeqdamAlqudah commented on index.html
> +        </nav>
- [ ] Please container of this section should be a `header` tag
- [ ] Please the hamburger button should be on the right and have a `nav` tag, there is no need to this a tag that contains the hamburger button.

2022-04-20 23:35 UTC, MeqdamAlqudah commented on index.html
> +        </nav>
- [ ] Please the header section should have the margins (top, bottom, left, right) defined in the [design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471)

| Your design | Figma design |
| ------------- | --------------- |
| ![image](https://user-images.githubusercontent.com/74744787/164340004-81429248-2870-4dd1-a4ea-aebbd4c451d2.png) | ![image](https://user-images.githubusercontent.com/74744787/164340163-72a4eea9-ea18-48c8-89e5-e18c0d731a5f.png) |

2022-04-20 23:35 UTC, MeqdamAlqudah commented on index.html
> +        </div>
- [ ] Please use the same font family for the logo as in Figma design 
![image](https://user-images.githubusercontent.com/74744787/164340296-20e696b3-95d3-4876-b6bf-908d8643f6e0.png)

2022-04-20 23:35 UTC, MeqdamAlqudah commented on index.html
> +        </nav>
- [ ] Please use CSS to set a background for your design 

![image](https://user-images.githubusercontent.com/74744787/164340441-d170db41-4e79-4a18-8f3a-4f7658b20e1a.png)

- [ ] Please make sure to fix this weird distance between the background and the paragraph and make it looks exactly as in Figma design 

| Your design | Figma design |
| ------------- | --------------- |
| ![image](https://user-images.githubusercontent.com/74744787/164340606-c36bc3b8-c937-4715-945a-01cd3c3de73a.png) | ![image](https://user-images.githubusercontent.com/74744787/164340654-cf1d45dd-b144-46a0-b09d-d1842703079c.png) |

2022-04-20 23:35 UTC, MeqdamAlqudah commented on index.html
> +                <p id="profession"> I’am a Software Developer</p>
- [ ] Please I don't see the goal of this header tag here header tag represents introductory content you can use div here instead.

2022-04-20 23:35 UTC, MeqdamAlqudah commented on index.html
> +        </div>
- [ ] Please design should have  margins (top, bottom, left, right) defined in the design

| Your design | Figma design |
| ------------- | --------------  |
| ![image](https://user-images.githubusercontent.com/74744787/164341197-a0b20c25-b50a-4676-bd1b-2b1dc48cbb8f.png) | ![image](https://user-images.githubusercontent.com/74744787/164341336-b2797fd0-c3e6-4e74-83c0-a8718b133b0a.png) |

2022-04-21 09:24 UTC, worashf commented
- Corrected the following

1. add   header for navigation and logo also css for it
2.  remove header from the head line 
3.  add the correct margin and padding for header
4.  correct the distance between the background image and the paragraph
5. add background image by css
6. corect the margin(top,bottom,left,right ) for head line

2022-04-21 10:01 UTC, m05e5 requested changes
Hi @worashf , 

You really did an amazing job!
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
You used proper GitHub Flow ✔️
All linters are passed ✔️

## Highlights


## Required Changes ♻️
* You really did a great job but there are some features you need to improve
  
- [ ] Your nav is overlapping the screen because of this padding, and because of that, we cannot see the hamburger menu unless we shift the screen right. I'll recommend you remove this padding and instead give some margin to the component inside the header(margin-left to "logo" and margin-right to "menu")

- [ ]  Also, because of this padding, the content is overflowing the screen size. As part of the requirement, I'll recommend putting instead some margin to the content. this will fix the overflowing content and background image. (CSS tip:` margin: top right bottom left;`)

_check below for more details_

_I'm sure you can do it just keep it up_
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- _(optional)_ I'll also recommend putting a short description of the project in the readme file.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 10:01 UTC, m05e5 commented on css/style.css
> +    padding: 0 24px;
- [ ] Your nav is overflowing the screen because of this padding, and because of that, we cannot see the hamburger menu unless we shift the screen right. I'll recommend you remove this padding and instead give some margin to the component inside the header(margin-left to "logo" and margin-right to "menu")
![image](https://user-images.githubusercontent.com/37901469/164427836-70d5dc3c-62c3-41a0-b5c9-5628c5448215.png)

2022-04-21 10:01 UTC, m05e5 commented on css/style.css
> +    padding: 120px 24px;
- [ ] Also, because of this padding, the content is overflowing the screen size. As part of the requirement, I'll recommend putting instead some margin to the content. this will fix the overflowing content and background image. (CSS tip: `margin: top right bottom left;`)
![image](https://user-images.githubusercontent.com/37901469/164430549-57a2c2b2-ef44-460c-ae94-ab8ab8ce7e1d.png)

2022-04-21 18:17 UTC, worashf commented
1.  remove padding from header
2. add margin in logo and menu
3. remove padding from head line container
4. add margin to head line contents

2022-04-21 18:24 UTC, youmari approved these changes
# Project Approved :trophy: :tada: 🟢 

Hi @worashf 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-21 18:30 UTC, merged